### PR TITLE
add tests for time and version plugins

### PR DESCRIPTION
**Pull request by sonnyp**

### CODE REVIEW

**Comment by ggozad** [comment]
I think these are good additions but it's hard to determine how useful they are outside testing simple get/set iq requests.
Perhaps deferring them until we test a more complex plugin such as the pubsub one is better.
Here are some specifics:
`fake()` should be kept to allow for receiving arbitrary stanzas, for example a headline message.
`sanitize()` should not always happen I think. For instance if we want to test a multiple request/response protocol such as the one we recently discussed where the id would be reused to signal a continuation of the original request.

In general I tend to disfavor the use of many different helper functions even if they reduce the code that needs to be written:
Consider for example the test for time/caller:
```
test('get', t => {
  t.context.scheduleIncomingResult(
    <time xmlns="urn:xmpp:time">
      <tzo>-06:00</tzo>
      <utc>2006-12-19T17:58:35Z</utc>
    </time>
  )

  return Promise.all([
    t.context.catchOutgoingGet().then(child => {
      t.deepEqual(child, <time xmlns="urn:xmpp:time" />)
    }),
    t.context.plugin.get().then(time => {
      t.deepEqual(time, {
        tzo: '-06:00',
        utc: '2006-12-19T17:58:35Z',
      })
    }),
  ])
})
```

The advantage of using ``scheduleIncomingResult`` is not clear to me. When I contrast it to simply catching the ``get``, asserting, then emitting the response, I think the second is more clear.
Would it also be better to have a generic catch, a generic emit, and a catch/emit that takes stanza type, type, and id as parameters? That would reduce the helpers to 4 functions.

Let me know if all this is unclear :)

**Comment by sonnyp** [comment]
> I think these are good additions but it's hard to determine how useful they are outside testing simple get/set iq requests.

They are specifically design to test simple get/set iq requests as we're gonna have lots more of them.

>  Perhaps deferring them until we test a more complex plugin such as the pubsub one is better.

My idea was to add more helpers and refine as we need them

>  fake() should be kept to allow for receiving arbitrary stanzas, for example a headline message.

agree

> sanitize() should not always happen I think. For instance if we want to test a multiple request/response protocol such as the one we recently discussed where the id would be reused to signal a continuation of the original request.

agree, the iq helpers are here to reduce the amount of boilerplate in tests (async, deleting id, the xmlns, ...) but it doesn't mean they have to be used for all iqs

> sanitize() should not always happen I think. For instance if we want to test a multiple request/response protocol such as the one we recently discussed where the id would be reused to signal a continuation of the original request.

In general I agree but for tests I tend to prefer reducing the amount of boilerplate/complexity so it doesn't become a burden writing tests, specially in an async context with a missing piece of software (server).

> The advantage of using scheduleIncomingResult is not clear to me. When I contrast it to simply catching the get, asserting, then emitting the response, I think the second is more clear.

`scheduleIncomingResult` simply emulate the server sending a response to the client request, there's no workaround that. Maybe I should rename it `scheduleFakeIncomingResult` ?

> Would it also be better to have a generic catch, a generic emit, and a catch/emit that takes stanza type, type, and id as parameters? That would reduce the helpers to 4 functions.

I agree we should have generic equivalents, I didn't included them here as I didn't need them and I prefer to add them as we need them. However I wouldn't remove the iq helpers as they reduce significantly the complexity and boilerplate for iq callee/caller tests.

**Comment by sonnyp** [comment]
If it's okay with you I'll merge this PR as is and introduce generic helpers in the next one as I'll need them for non iq plugins tests

**Comment by ggozad** [comment]
All good here, please merge and we'll add stuff later.

**Pull request merged**
