### PR TITLE
Improve TLSv1.3 compatibility

### PR DESCRIPTION
**Pull request by netmikey**
As discussed in https://github.com/xmppjs/xmpp.js/issues/889

### CODE REVIEW

**Comment by sonnyp** [comment]
Don't worry about CI, I will fix the tests

**Comment by sonnyp** [comment]
This PR breaks prosody with `xmpp:`, `xmpps:` and `WebSocket:`

Screenshot from 2021-08-21 23-16-28

If you want to upstream this you'll have to do the following

1. CI should pass (you can test locally with `make test-ci` after installing prosody)
2. The fix shouldn't break other servers
3. Add a test see https://github.com/xmppjs/xmpp.js/issues/889#issuecomment-902786001

**Comment by sonnyp** [comment]
Indeed, whitespaces are not allowed before opening the stream

>. MAY send whitespace as separators between XML stanzas or between any other first-level elements sent over the stream

I guess you'll have to find an other workaround or fix.

Have you tried to write an empty string?

**Comment by netmikey** [comment]
You're right, I was reading that exact same part of the spec while you were replying 😊

I tried with an empty message and it also seems to fix the issue with Openfire's TLSv1.3. This should be even less impactful than the white space. I don't have prosody installed, so let's see if that fixes CI...

**Comment by sonnyp** [comment]
For the record all you need to do is `brew install prosody`. `make test-ci` takes care of configuring, starting, ... I have not tried on macOS though so no guarantees there.

These workaround also worth trying

```
await Promise.resolve();
```


```
await new Promise(resolve => setTimeout(resolve, 500));
```

**Comment by netmikey** [comment]
Looks like even the empty network packet broke CI tests. Your ideas were great though, while `await Promise.resolve();` didn't work (I guess the runtime short-circuits this), the second variant `await new Promise(resolve => setTimeout(resolve, 1));` worked, even with only 1ms of delay. I guess it suffices to wait for the next tick of the runloop before sending the first packet. So weird...

Now that we don't send anything anymore over the network, this should reeeeealy not have any externally visible impact anymore.

**Comment by sonnyp** [comment]
I have found a flaw in xmpp.js TLS handling that may solve this without the need for a workaround.

I will fix it first to see if it solves your issue. :crossed_fingers: 

If not, we can get this in.

**Comment by sonnyp** [comment]
Could you try with a (fresh) install of xmpp.js 0.12.1 ?

https://github.com/xmppjs/xmpp.js/releases/tag/v0.12.1

**Comment by netmikey** [comment]
I tested it with 0.12.1, unfortunately it behaves the same with the regard to the TLSv1.3 connection hanging.

"Fortunately", the one-liner proposed in the latest version of this PR still seems to fix it ;-)

**Comment by sonnyp** [comment]
Couldn't push to this branch for some reason - closing in favor of https://github.com/xmppjs/xmpp.js/pull/914

**Pull request closed without merging**
