### PR TITLE
@xmpp/middleware

### PR DESCRIPTION
**Pull request by sonnyp**
cc @smokku 

Inspired by junction and koa

Goals

* works for both incoming and outgoing stanzas
* async
* well known API
* easy match (see router plugin)
* works for client, component and server

Notes

* what if it was possible to "middleware" any event? online, authenticate, ...
* should handling incoming and outgoing stanzas be 2 separate plugins?
* most plugins could be rewritten as middlewares (and benefit from it)
* for the ones that cannot (callers) maybe `require('@xmpp/ping')(entity, to)` ? - probably no need for current plugin system here

### CODE REVIEW

**Comment by smokku** [comment]
Keeping plugin/middleware separation could be beneficial.

*jabberd2* which I am most familiar with, has a similar separation of SX (eXtensible Stream) and Packet Chains.
SX is a pluggable system dealing with XMPP byte streams - there are plugins handling TLS, compression, SASL, ACK, WebSocket wrapping. Stacked together they deal with delivering bytes (in byte buffers) wrapping/unwrapping between the network to XML parser and from XML serializer to the network.
Chains are on the other side of the parser and deal with parsed stanzas. There are separate chains processing stanzas depending on where the stanza came from and where it is going to. Each step of the chain is able to take a look at stanza, modify it before passing on, generate reply and decide whether the chain is done with stanza.

I like this separation. SX does not deal with the content of the stanza, just makes sure stanzas are received and delivered properly. Chains on the other hand are interested in the content only, and do not care how (or even if at all) stanzas are transported.

Just a food for thought.

**Comment by sonnyp** [comment]
@smokku nice input, thanks

So far I'm planning on removing the plugin API and use the following signature

```js
function plugin(entity) {
  // do something with entity
}

const client = ...
plugin(client)
```

So we can get rid of the weird plugin API and have something more functional and natural.

**Comment by sonnyp** [comment]
That's how `@xmpp/middleware` and `@xmpp/router` are written and I'm planning on rewriting the other plugins.

**Comment by smokku** [comment]
> plugin(client)

Looks like a very tight coupling. Instead of simply implementing a plugin interface, this kind of `plugin()` needs an intimate knowledge of `client` APIs and most probably internals and sequences. And when these change, all plugins (even 3rd party ones) need to change?

**Comment by sonnyp** [comment]
@smokku it's already the case now, what's the alternative?

**Comment by smokku** [comment]
Yes, you're right. Plugin has to hook-in to all the event streams and there is not much we can do. 
You just exposed this tight coupling, which is actually good as it does make it obvious not giving false expectations.

**Comment by sonnyp** [comment]
@smokku yes plus the coupling is not that bad as you can take something else than the entity/client as input

for example https://github.com/xmppjs/xmpp.js/pull/490/files#diff-93769b00d143febe908b3562c24f3106R28

**Pull request merged**
