### PR TITLE
Include CommonJS, ESM and UMD builds in all packages

### PR DESCRIPTION
**Pull request by wichert**
We currently can not use the various @xmpp/* packages, because their release on npmjs is not compiled properly, resulting in a lot of webpack errors. This PR tries to fix that by using [rollup](https://rollupjs.org/) to build and publish everything in CommonJS, ESM and UMD formats.

This required a small bit of code restructuring: rollup was very unhappy with `index.js` being in the package root, so I moved it into `lib/` everywhere.

### CODE REVIEW

**Comment by wichert** [comment]
I forgot to mention: this can (and perhaps should?) replace the existing bundling system for the xmpp.js bundle package.

**Comment by wichert** [comment]
FWIW the travis failure is not related to changes from this PR.

**Comment by sonnyp** [comment]
> their release on npmjs is not compiled properly

What do you mean? They are not compiled at all. They are written for commonjs.

All you have to do is make sure they go through babel or typescript. If you tell me more about the setup I can probably help with that.

> This PR tries to fix that by using rollup to build and publish everything in CommonJS, ESM and UMD formats.

Thanks! I would like to have this eventually but not before moving away from commonjs to modules.

**Comment by wichert** [comment]
@sonnyp The fact that they are not compiled at all is exactly the problem - it is breaking our ability to use those packages. Babel (and TypeScript) do not process anything in node_modules: they expect everything in there to already be compiled.

**Comment by sonnyp** [comment]
The default behavior depends on the setup. For example, CRNA/expo default is to compile `node_modules`.

I gave a very simple solution to the problem. If it does not work for you please let me know why and I'll be happy to reconsider.

It's good practice to compile code from node_modules anyway, specially for the browser because you never know which ECMAScript version is targeted by the author; it might not be compatible with your target.

**Comment by wichert** [comment]
A counter-example: Create-React-App, which is probably one of the most popular frameworks for frontside development, does not compile anything in node_modules.

**Comment by sonnyp** [comment]
> Thanks! I would like to have this eventually but not before moving away from commonjs to modules.

> I gave a very straightforward solution to the problem. If it does not work for you please let me know why and I'll be happy to reconsider.

**Comment by wichert** [comment]
It does not work for me because we use create-react-app, which refuses to compile in node_modules.

**Comment by sonnyp** [comment]
@wichert I just tried myself, [CRA](https://github.com/facebook/create-react-app) does compile `node_modules` and I was able to use an `@xmpp` package without any additional configuration:

```sh
npx create-react-app my-app
cd my-app
npm install @xmpp/error
```

edit `src/app.js`

```js
import error from '@xmpp/error'

console.log(error)
```

```sh
npm start
```

Screenshot from 2019-07-16 16-08-42

**Comment by sonnyp** [comment]
Just tried with something more complex, `@xmpp/client-core`, also works.

**Comment by sonnyp** [comment]
Same with `npx create-react-app my-app --typescript`:

Screenshot from 2019-07-16 16-17-05

**Comment by sonnyp** [comment]
@wichert did you find the issue and a solution?

**Pull request closed without merging**
