### PR TITLE
Pusub plugin

### PR DESCRIPTION
**Pull request by ggozad**
Preliminary implementation of basic pubsub. There are quite a few things missing, notably events, but you should be able to create, delete, publish and retrieve from nodes.

### CODE REVIEW

**Comment by ggozad** [comment]
I would like to add to this handling of pubsub events. Do we have an example of how events should be triggered from a plugin? Should the plugin be an EventEmitter or should it use the connection?

**Comment by sonnyp** [comment]
@ggozad cool!

plugin is already an EventEmitter, you can use `this.emit`

**Comment by sonnyp** [comment]
actually plugins inherit from https://github.com/node-xmpp/node-xmpp/blob/master/packages/events/lib/EventEmitter.js which is not a Node.js EventEmitter but is API compatible

**Comment by ggozad** [comment]
Excellent will have a look.

**Comment by ggozad** [comment]
Need some help with events. I would like to be able to handle PEP events for pubsub. These are message stanzas with the attribute from being the pubsub service. My guess is that one would use the stanzaRouter for such a thing.
At which point and how would you register with stanzaRouter? The user would need to pass the name of the pubsub service that he wants to receive events from.

**Comment by ggozad** [comment]
Simplest thing would probably be to do a 
``
module.exports = function (service) { } 
``
instead of returning the plugin initialised. But that would break the symmetry of how we init plugins...

**Comment by ggozad** [comment]
@sonnyp if you can have a look at how events are handled and triggered and offer an opinion then I can add more. Notably:
1) The plugin needs now to be initialised with a service name (see tests)
2) plugin listens for PEP messages and triggers events on the client.

**Comment by sonnyp** [comment]
https://github.com/xmppjs/xmpp.js/pull/487

**Pull request closed without merging**
