### PR TITLE
Support "legacySSL" connections server-side

### PR DESCRIPTION
**Pull request by stela**
The XMPP client library supports direct/"native" SSL/TLS connections, where you don't need the STARTTLS feature, however server-side that feature is missing.

Here's a patch to add support for that. Feel free to clean up/modify the patch, it's my first Node.js code.

### CODE REVIEW

**Comment by sonnyp** [comment]
thanks, out of curiosity, what do you need this for?

**Comment by stela** [comment]
@sonnyp Have a mobile client which normally connects to the ejabberd XMPP server using SSL/TLS directly (no STARTTLS). We want to make some integration tests using a node-xmpp-based stub server, so would be great to have this feature built-into the library.

As I'm a JavaScript newbie though, I have trouble figuring out why the test case fails on Node.js 0.12 but works fine with the other three versions on travis-ci. Can you guys help me out?

**Comment by stela** [comment]
Found a comment about the failing test in https://github.com/node-xmpp/node-xmpp/pull/304#issuecomment-225625950, that explains it then, it's a known issue.

**Comment by sonnyp** [comment]
@stela LGTM have you tested this with your mobile client yet?

**Comment by stela** [comment]
No, the mobile client isn't quite ready for testing yet. But the server responded as when using the unencrypted connection when connecting with "openssl s_client" and typing in `<stream:stream to="asdf">bla bla...` and there's a test case where the XMPP client manages to authenticate.

**Comment by sonnyp** [comment]
closing this, node-xmpp is not supported anymore

**Pull request closed without merging**
